---
# tasks file for haproxy_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install haproxy package
  become: true
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration template
  template:
    src: "{{ role_path }}/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Ensure haproxy service is running and enabled
  service:
    name: haproxy
    state: restarted
    enabled: yes
