---
# tasks file for haproxy_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install haproxy package
  become: true
  apt:
    name: haproxy
    state: present

- name: Copy haproxy configuration files
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg

- name: Ensure haproxy service is running and enabled
  service:
    name: haproxy
    state: started
    enabled: yes
